### ISSUE TITLE
Hi Cooolallen, I have this error. You help me

### ISSUE THREAD

**Issue by thanhphongpham** [cooolallen/CVFinal#3]
Hi Cooolallen
I have this error, while run it. You help me.
Use the retry module or similar alternatives.
Traceback (most recent call last):
File "Top.py", line 186, in 
FR.build()
File "D:\test\CacTacGia\cooolallen\cooolallen\FaceRecognizer.py", line 164, in build
logits, _ = network.inference(self._images_placeholder, phase_train=False)
TypeError: inference() missing 1 required positional argument: 'keep_probability'

**Comment by thanhphongpham** [comment]
I found out that "def inference (images, keep_probability, phase_train = True,
               bottleneck_layer_size = 128, weight_decay = 0.0, reuse = None) "
What is keep_probability?
What is it at?
